# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MP3-Find
version:      0.01
version_from: lib/MP3/Find.pm
installdirs:  site
requires:
    File::Find:                    0
    MP3::Info:                     0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
